"""
Mock FIR Historical Database containing realistic police records with cross-case links,
repeat offender signatures, and diverse crime categories.
"""

from typing import List, Dict, Any
from core.fir_backend.models import EntityExtraction

HISTORICAL_FIRS: List[Dict[str, Any]] = [
    {
        "case_id": "FIR-2024-0812",
        "police_station": "Indiranagar PS, Bengaluru",
        "date_time": "2024-03-12 19:45",
        "crime_type": "Snatching / Robbery",
        "legal_sections": ["IPC 392 (Robbery)", "IPC 34 (Common Intention)"],
        "complainant": "Sunita Rao",
        "victims": ["Sunita Rao"],
        "accused_suspects": ["Bunty @ Rakesh", "Kallu @ Vikram (Pillion)"],
        "location": "100 Feet Road, near CMH Junction, Indiranagar",
        "city_zone": "East Zone",
        "modus_operandi": "Two men on a black Bajaj Pulsar motorcycle without a front number plate approached lone female pedestrian from behind. Pillion rider wearing a red full-face helmet grabbed gold mangalsutra chain from victim's neck while driver accelerated at high speed towards Old Madras Road.",
        "mo_entry_exit": "Approached on moving bike, fled towards arterial highway",
        "mo_pretext_trick": "Sudden approach from blind spot",
        "mo_transport": "Black Bajaj Pulsar bike (Plate partly taped: KA-03-??-4812)",
        "mo_timing_profile": "Evening dusk (19:00 - 20:30)",
        "mo_target_profile": "Lone woman walking on poorly lit pavement",
        "weapons": ["None displayed (Physical force)"],
        "vehicles_involved": ["Black Bajaj Pulsar (Partial: KA-03-??-4812)"],
        "stolen_property": ["Gold chain with pendant (approx 28 grams, Rs 1.8 Lakh)"],
        "phone_numbers": [],
        "raw_text": "To the Station House Officer, Indiranagar Police Station. Respected Sir, I Sunita Rao, aged 42 years, resident of Indiranagar, state that on 12/03/2024 around 7:45 PM while returning from grocery market on 100 Feet Road, two unidentified men on a black Pulsar motorcycle came close. The pillion rider wore a red helmet and violently snatched my gold mangalsutra weighing 28 grams. The driver had muffled his face with a black scarf. They sped away towards Old Madras Road. Bystanders noted partial bike registration KA-03 with ending digits 4812. Kindly register FIR."
    },
    {
        "case_id": "FIR-2024-0945",
        "police_station": "Koramangala PS, Bengaluru",
        "date_time": "2024-03-28 20:15",
        "crime_type": "Snatching / Robbery",
        "legal_sections": ["IPC 392 (Robbery)", "IPC 397 (Robbery with deadly weapon)"],
        "complainant": "Deepika Nair",
        "victims": ["Deepika Nair"],
        "accused_suspects": ["Bunty @ Rakesh (Driver)", "Kallu @ Vikram (Pillion)"],
        "location": "5th Block, near Jyoti Nivas College Road, Koramangala",
        "city_zone": "South-East Zone",
        "modus_operandi": "Two motorcycle-borne youth rode onto the footpath on a black Bajaj Pulsar (KA-03-HX-4812). Pillion wearing red helmet brandished a folded button knife to intimidate victim and snatched gold necklace and iPhone 14. Suspects fled towards Dairy Circle flyover.",
        "mo_entry_exit": "Mounted pavement, rapid escape towards flyover",
        "mo_pretext_trick": "Cornered pedestrian against compound wall",
        "mo_transport": "Black Bajaj Pulsar 220 (KA-03-HX-4812)",
        "mo_timing_profile": "Night (20:00 - 21:00)",
        "mo_target_profile": "Young female pedestrian with handheld mobile and jewelry",
        "weapons": ["Button knife / spring knife"],
        "vehicles_involved": ["KA-03-HX-4812 (Bajaj Pulsar)"],
        "stolen_property": ["Gold necklace (22 grams)", "Apple iPhone 14 Midnight Black"],
        "phone_numbers": [],
        "raw_text": "Complaint by Deepika Nair: Today 28th March around 8:15 PM while walking near Jyoti Nivas College, two bike riders stopped beside me. The pillion wearing red helmet flashed a knife and grabbed my gold chain and snatched my iPhone. The bike was a black Pulsar with registration KA-03-HX-4812. They escaped toward Dairy Circle. Request immediate action."
    },
    {
        "case_id": "FIR-2024-1102",
        "police_station": "Cyber Crime PS, Bengaluru CID",
        "date_time": "2024-04-05 11:30",
        "crime_type": "Cyber Fraud / Financial Scam",
        "legal_sections": ["IT Act 66D (Cheating by impersonation)", "IPC 420 (Cheating)"],
        "complainant": "Venkatesh Murthy",
        "victims": ["Venkatesh Murthy"],
        "accused_suspects": ["Manoj Kumar @ Rajat (Caller)", "Ramesh Shah (Account Holder)"],
        "location": "Online / Digital (Victim resident of Jayanagar)",
        "city_zone": "Cyber Cell",
        "modus_operandi": "Victim received an SMS claiming electricity power supply would be disconnected tonight due to unpaid previous month bill. Victim was instructed to call +91-9876543210. Caller impersonating BESCOM electricity officer asked victim to download 'BESCOM QuickPay.apk' via WhatsApp. The remote screen mirroring app siphoned Rs 4.5 Lakhs from SBI account.",
        "mo_entry_exit": "Phishing SMS followed by social engineering & malicious APK installation",
        "mo_pretext_trick": "Urgent utility bill disconnection threat (Electricity)",
        "mo_transport": "None (Virtual/Cyber)",
        "mo_timing_profile": "Daytime morning (10:00 - 12:00)",
        "mo_target_profile": "Elderly bank account holders",
        "weapons": ["None (Malware / AnyDesk APK)"],
        "vehicles_involved": [],
        "stolen_property": ["INR 4,50,000 transferred to mule accounts"],
        "phone_numbers": ["+91-9876543210", "+91-9811223344"],
        "raw_text": "Complainant Venkatesh Murthy reports that on 05/04/2024 at 11:30 AM he received SMS from phone +91-9876543210 warning of immediate electricity cutoff. Upon calling, accused identified as Rajat from Electricity Board guided him to install APK file from WhatsApp link. Within 15 minutes, three unauthorized NEFT transfers totaling Rs 4.5 Lakh were transacted from his SBI savings account to mule account of Ramesh Shah."
    },
    {
        "case_id": "FIR-2024-1240",
        "police_station": "Cyber Crime PS, Bengaluru CID",
        "date_time": "2024-04-18 15:20",
        "crime_type": "Cyber Fraud / Financial Scam",
        "legal_sections": ["IT Act 66D", "IPC 420 (Cheating)", "IPC 120B (Criminal Conspiracy)"],
        "complainant": "Anand Kulkarni",
        "victims": ["Anand Kulkarni"],
        "accused_suspects": ["Manoj Kumar @ Rajat", "Unknown Jamtara Syndicate"],
        "location": "Online / Digital (Victim resident of Malleshwaram)",
        "city_zone": "Cyber Cell",
        "modus_operandi": "SMS phishing: 'Dear Consumer, your electricity bill is unpaid, power will be suspended at 9:30 PM. Contact officer at +91-9876543210'. Victim contacted number, scammer sent malicious remote APK named 'UrjaSahay.apk'. Money siphoned across 4 transactions totaling Rs 3.8 Lakh.",
        "mo_entry_exit": "Phishing SMS, WhatsApp APK distribution, OTP interception",
        "mo_pretext_trick": "Utility disconnection notice (Urja/Power)",
        "mo_transport": "None (Virtual)",
        "mo_timing_profile": "Afternoon (14:00 - 16:00)",
        "mo_target_profile": "Senior citizen homeowner",
        "weapons": ["Remote access APK spyware"],
        "vehicles_involved": [],
        "stolen_property": ["INR 3,80,000"],
        "phone_numbers": ["+91-9876543210"],
        "raw_text": "Anand Kulkarni received fake electricity warning from number +91-9876543210. Scammer claiming to be technical officer sent APK on WhatsApp. Screen got locked while OTPs were read and total Rs 3.8 lakhs debited from PNB account."
    },
    {
        "case_id": "FIR-2024-1315",
        "police_station": "HSR Layout PS, Bengaluru",
        "date_time": "2024-04-22 03:15",
        "crime_type": "House Burglary / Breaking by Night",
        "legal_sections": ["IPC 457 (Lurking house-trespass by night)", "IPC 380 (Theft in dwelling house)"],
        "complainant": "Rajiv Mehra",
        "victims": ["Rajiv Mehra and family"],
        "accused_suspects": ["Chaddi Baniyan Gang / Iron Rod Syndicate (3 unidentified men)"],
        "location": "Sector 2, HSR Layout, Independent Villa #412",
        "city_zone": "South-East Zone",
        "modus_operandi": "Perpetrators targeted corner independent house locked while family was out of town. Cut through ground floor rear kitchen window iron security grill using hydraulic bolt cutter. Ransacked master bedroom almirah, disabled CCTV DVR unit by cutting power cords, and escaped through rear boundary wall.",
        "mo_entry_exit": "Cut rear kitchen window grill, exited through rear boundary wall",
        "mo_pretext_trick": "Recce of locked houses with stacked newspaper/uncollected parcels",
        "mo_transport": "White Maruti Swift Dzire (Fake registration number)",
        "mo_timing_profile": "Dead of night (02:30 - 04:00 AM)",
        "mo_target_profile": "Locked independent villa during school vacation",
        "weapons": ["Hydraulic bolt cutter", "Iron crowbar"],
        "vehicles_involved": ["White Maruti Swift Dzire"],
        "stolen_property": ["Gold ornaments (140 grams)", "Diamond necklace set", "Cash Rs 2,50,000"],
        "phone_numbers": [],
        "raw_text": "Rajiv Mehra returned from holiday to find house burglarized. Rear window grill of kitchen was cut neatly with bolt cutter. Lockers broken in bedroom. CCTV unit smashed and hard drive missing. Gold jewelry and cash stolen. White Swift car seen lingering in street at 3:15 AM on neighbor's camera."
    },
    {
        "case_id": "FIR-2024-1420",
        "police_station": "Bellandur PS, Bengaluru",
        "date_time": "2024-05-02 02:45",
        "crime_type": "House Burglary / Breaking by Night",
        "legal_sections": ["IPC 457", "IPC 380", "IPC 411"],
        "complainant": "Siddharth Verma",
        "victims": ["Siddharth Verma"],
        "accused_suspects": ["Iron Rod Syndicate (3 masked men)"],
        "location": "Green Glen Layout, Bellandur",
        "city_zone": "East Zone",
        "modus_operandi": "Three masked men carrying heavy backpacks entered independent ground floor bungalow through rear utility area. Ground floor iron grill bars severed with industrial bolt cutter. Master bedroom Godrej steel almirah pried open using heavy crowbar. DVR of surveillance system disconnected and stolen.",
        "mo_entry_exit": "Rear utility grill cut with bolt cutter, rear garden wall exit",
        "mo_pretext_trick": "Night surveillance of vacant property",
        "mo_transport": "White Maruti Swift Dzire parked 200m away on main road",
        "mo_timing_profile": "Late night (02:00 - 03:30 AM)",
        "mo_target_profile": "Unoccupied ground floor residence",
        "weapons": ["Industrial bolt cutter", "Heavy crowbar"],
        "vehicles_involved": ["White Maruti Swift Dzire"],
        "stolen_property": ["Gold jewelry (95 grams)", "Cash Rs 1,80,000", "Rolex watch"],
        "phone_numbers": [],
        "raw_text": "Complainant Siddharth Verma reported housebreaking at Green Glen Layout. Family was attending wedding in Mysore. Burglar cut utility window iron rods with heavy cutter. Prized open lockers. Neighbors camera recorded 3 masked men loading bags into white Swift car around 2:50 AM."
    },
    {
        "case_id": "FIR-2024-1508",
        "police_station": "Whitefield PS, Bengaluru",
        "date_time": "2024-05-14 13:30",
        "crime_type": "Pretext Robbery / Impersonation",
        "legal_sections": ["IPC 392 (Robbery)", "IPC 419 (Cheating by impersonation)"],
        "complainant": "Shailaja Swaminathan",
        "victims": ["Shailaja Swaminathan (68 yrs)"],
        "accused_suspects": ["Pradeep @ Sonu (Courier Impersonator)", "Associate in helmet"],
        "location": "ECC Road, Whitefield",
        "city_zone": "Whitefield Division",
        "modus_operandi": "Accused dressed in courier delivery t-shirt (Blue Dart/Delhivery logo) rang doorbell holding a large taped cardboard box addressed to victim's son. Asked elderly victim for glass of water and pen for delivery signature. Once door opened wide, accused barged inside, pushed victim to couch, held utility cutter to her throat, and snatched gold bangles and mangalsutra.",
        "mo_entry_exit": "Front door entry via fake parcel pretext, escaped on scooter",
        "mo_pretext_trick": "Fake courier delivery parcel asking for water/signature",
        "mo_transport": "Grey Honda Activa scooter (Plate smeared with mud)",
        "mo_timing_profile": "Midday afternoon (12:30 - 14:00) when men are at work",
        "mo_target_profile": "Elderly woman home alone in gated apartment/villa",
        "weapons": ["Box cutter / utility blade"],
        "vehicles_involved": ["Grey Honda Activa (Mud obscured plate)"],
        "stolen_property": ["4 Gold bangles (40 grams)", "Gold mangalsutra", "Diamond earrings"],
        "phone_numbers": ["+91-9741009988"],
        "raw_text": "Shailaja Swaminathan, aged 68, states that at 1:30 PM a person posing as courier delivery boy wearing courier company jacket came with parcel for her son. He asked for water. When she opened the security grill, he forcefully entered, brandished a box cutter knife, threatened to kill her, and forcibly removed her 4 gold bangles and necklace. He escaped on a grey Activa scooter where an accomplice was waiting."
    },
    {
        "case_id": "FIR-2024-1622",
        "police_station": "Mahadevapura PS, Bengaluru",
        "date_time": "2024-05-29 14:00",
        "crime_type": "Pretext Robbery / Impersonation",
        "legal_sections": ["IPC 392", "IPC 419", "IPC 34"],
        "complainant": "Geetha Balakrishnan",
        "victims": ["Geetha Balakrishnan (71 yrs)"],
        "accused_suspects": ["Pradeep @ Sonu", "Accomplice on scooter"],
        "location": "Garudachar Palya, Mahadevapura",
        "city_zone": "Whitefield Division",
        "modus_operandi": "Perpetrator wearing courier polo shirt knocked on door carrying dummy Amazon carton. Asked elderly homemaker for delivery verification code and glass of drinking water. Pushed open door, brandished sharp box cutter, tied victim's hands with zip-ties, and robbed gold jewelry from bedroom dressing table.",
        "mo_entry_exit": "Front entrance via fake parcel delivery pretext",
        "mo_pretext_trick": "Dummy ecommerce courier delivery asking for water/OTP",
        "mo_transport": "Grey Honda Activa scooter (KA-53-EJ-9014)",
        "mo_timing_profile": "Early afternoon (13:30 - 15:00)",
        "mo_target_profile": "Senior citizen woman living alone",
        "weapons": ["Utility box cutter", "Plastic zip-ties"],
        "vehicles_involved": ["Grey Honda Activa (KA-53-EJ-9014)"],
        "stolen_property": ["Gold chains (2 numbers, 35 grams)", "Gold ear studs", "Cash Rs 40,000"],
        "phone_numbers": ["+91-9741009988"],
        "raw_text": "Complaint by Geetha Balakrishnan: At 2 PM delivery boy with Amazon parcel asked for water. He entered forcefully, showed box cutter, restrained me with zip ties, took gold jewelry and cash. He received a phone call from +91-9741009988 saying 'Hurry up Sonu'. They fled on grey Activa KA-53-EJ-9014."
    },
    {
        "case_id": "FIR-2024-1750",
        "police_station": "Jayanagar PS, Bengaluru",
        "date_time": "2024-06-10 20:30",
        "crime_type": "Snatching / Robbery",
        "legal_sections": ["IPC 392", "IPC 34"],
        "complainant": "Kavita Rao",
        "victims": ["Kavita Rao"],
        "accused_suspects": ["Bunty @ Rakesh", "Kallu @ Vikram"],
        "location": "4th Block, near Cool Joint, Jayanagar",
        "city_zone": "South Zone",
        "modus_operandi": "Two men riding high-performance black Bajaj Pulsar motorcycle. Pillion wearing red helmet snatched gold chain of victim waiting near bus stop. Rider accelerated aggressively towards Kanakapura main road.",
        "mo_entry_exit": "Rode up behind victim, fled via main arterial road",
        "mo_pretext_trick": "Snatch-and-run at bus stop shadow",
        "mo_transport": "Black Bajaj Pulsar 220 (KA-03-HX-4812)",
        "mo_timing_profile": "Night (20:00 - 21:30)",
        "mo_target_profile": "Female commuter waiting at bus stop / corner",
        "weapons": ["None displayed"],
        "vehicles_involved": ["Black Bajaj Pulsar (KA-03-HX-4812)"],
        "stolen_property": ["Gold chain (30 grams)"],
        "phone_numbers": [],
        "raw_text": "Kavita Rao complains that while waiting for auto near Cool Joint in Jayanagar 4th Block at 8:30 PM, two men on black Pulsar bike KA-03-HX-4812 snatched her 30g gold chain. Pillion had a distinct red helmet. Accused sped towards South End Circle."
    },
    {
        "case_id": "FIR-2024-1880",
        "police_station": "Electronic City PS, Bengaluru",
        "date_time": "2024-06-25 03:30",
        "crime_type": "Automobile Theft / Vehicle Lifting",
        "legal_sections": ["IPC 379 (Theft)"],
        "complainant": "Arun Kumar",
        "victims": ["Arun Kumar"],
        "accused_suspects": ["Mewat Car Theft Gang (2 tech-equipped car lifters)"],
        "location": "Phase 1, Neeladri Road, Electronic City",
        "city_zone": "Electronic City Division",
        "modus_operandi": "Perpetrators targeted Hyundai Creta SUV parked on residential street. Smashed quarter-glass window using spark-plug ceramic shard to prevent alarm. Connected electronic OBD (On-Board Diagnostics) device to reprogram transponder key within 4 minutes. Used RF signal jammer to block GPS tracker before driving vehicle away.",
        "mo_entry_exit": "Silent window pop, OBD key reprogramming, GPS jammer",
        "mo_pretext_trick": "High-tech key cloning without original key",
        "mo_transport": "Stolen Hyundai Creta (KA-51-MD-3301)",
        "mo_timing_profile": "Early hours (03:00 - 04:30 AM)",
        "mo_target_profile": "High-demand SUV parked outside residential apartment",
        "weapons": ["Ceramic spark plug glass breaker", "OBD key programmer tool", "GPS jammer"],
        "vehicles_involved": ["Hyundai Creta White (KA-51-MD-3301)"],
        "stolen_property": ["Hyundai Creta 2023 SX(O) valued at Rs 18,50,000"],
        "phone_numbers": [],
        "raw_text": "Complainant Arun Kumar parked his Hyundai Creta KA-51-MD-3301 outside society gate. In morning vehicle was missing. CCTV footage shows two suspects in hoodies breaking small rear quarter window without sound, plugging gadget into steering column, and starting car within 4 minutes. GPS tracker showed signal lost at 3:35 AM."
    }
]


def get_all_historical_firs() -> List[EntityExtraction]:
    """Return all historical cases as structured EntityExtraction models."""
    return [EntityExtraction(**case) for case in HISTORICAL_FIRS]


def add_historical_fir(fir: EntityExtraction) -> None:
    """Add a new FIR into the in-memory database."""
    HISTORICAL_FIRS.append(fir.model_dump())
